databases:
  - name: postgres
    ipAllowList: []
    databaseName: tech_tales
    user: tech_tales

services:
  - type: web
    name: tech_tales
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false